### ISSUE TITLE
Mantis server seg fault

### ISSUE THREAD

**Issue by zsxing99** [giorgk/Mantis#11]
After a little investigation, the segfault happened when one of the `scenarios` is not correctly loaded (second level data file), but it is requested in the input message.

I think it will be better if the Mantis server fails to start when there is an error loading a second-level data file from the top-level configuration file.

**Comment by giorgk** [comment]
What do you mean by second-level data file?
Can you be specific about the file that fails to load? Maybe there is an issue in the reading process

**Comment by giorgk** [comment]
Do you still have this problem?
If there is an issue while reading the following line should return false and exit
https://github.com/giorgk/Mantis/blob/5de9241da3f2e9e9e6e1efe0920bdbe7d048d814/CPP/MantisServer/MantisServer/MantisServer.cpp#L43

Maybe there is an error somewhere and the false output does not propagate all the way to this line

**Comment by zsxing99** [comment]
I will test this with more input

**Comment by zsxing99** [comment]
I don't find this error anymore. This issue can be closed for now.
