### ISSUE TITLE
Clarify the Units of the loading functions

### ISSUE THREAD

**Issue by giorgk** [giorgk/Mantis#3]
What are the units of NGWs? 
If they are mg/l then the code is ok.
if they are expressed ad kg/area then they must be converted first and there is no such conversion in the code at the moment

**Comment by giorgk** [comment]
For GNLM I assume that the data in each pixel are in kg/ha/year
Therefore to convert them to mg/l I do the following:

C[mg/L] =N [kg/ha/year]*100/RCH[mm/year]

Can anyone @thharter @chrishenri confirm that?

**Comment by thharter** [comment]
Giorgos,

I am confirming that this is correct.

In 1 year on 1 hectare:

1 mm of water on 1 ha is 10,000 liters of water.
1 kg in 10,000 L is 100 mg in 1 L.

So your conversion is correct: C = N * 100/RECH

For example:  if N is 100 kg/ha/year and recharge is 300 mm/year, then c =
100*100/300 = 33 mg/L NO3-N

Another example related to the N loading "yardstick":  30 kg/ha/year N
loading in 300 mm/year recharge (a typical recharge in irrigated crops) =
30*100/300 = 10 mg/L of NO3-N (the MCL).

Thank you for checking!
Thomas
----
Thomas Harter
ph/ 530-400-1784
http://groundwater.ucdavis.edu
