### ISSUE TITLE
Mantis output contains '-nan'

### ISSUE THREAD

**Issue by zsxing99** [giorgk/Mantis#6]
Input file: https://github.com/giorgk/Mantis/blob/master/CPP/TestClient/incomingMsg.dat 
Output file: https://github.com/zsxing99/Mantis/blob/error-report/data/error/sample.txt

Run with the TestClient according to the instructions.

The output file contains around 1000 '-nan' values.

**Comment by giorgk** [comment]
The problem occurs when the standard deviation in one of the well streamlines is 0
I have to update the input file

**Comment by giorgk** [comment]
Grab the latest input data set from the Gdrive/Mantis/Local/ServerData
In my run I didn't get any `nan` values.

Make sure also that you get the latest version of the code although I haven't change anything important.
You can now pass two different scenario names `CVHM_92_03_bud0` or `CVHM_92_03_bud1`

**Comment by zsxing99** [comment]
ok, will take a look and re-run the program

**Comment by zsxing99** [comment]
Tested `bud0` and `bud1` dataset with the TestClienet, they all produce valid numbers and worked well.

**Comment by zsxing99** [comment]
An additional config problem was found and mentioned in #7
