### ISSUE TITLE
Carriage return tolerance of data files

### ISSUE THREAD

**Issue by zsxing99** [giorgk/Mantis#7]
Since the system is deployed on Linux, it would be more consistent that the data loading program will tolerate carriage return `\r` (a Vim preference at the end of lines) to split lines and reading data.

Currently, the program use cpp `getline` functions to read the `wells.mnts` and `urf.mnts` and `getline` can only split newline `\n`, so it makes reading data sometimes very buggy as I spend a long time to identify the issue. 

Otherwise, it will be great if we can warn the users if they are use `\r` instead of `\n`.

**Comment by zsxing99** [comment]
To covert or remove carriage return, try `sed -e "s/\r//g" file > newfile`.

**Comment by zsxing99** [comment]
The issue results from `getline` and `ifstream.open`. If the `mnts` files are written by vim program, each line will end with a `\r\n`. Lines extracted by `getline` will only trunate `\n`, so it makes `ifstream.open` unable to locate the file, and fail to open it because of the tailing `\r` value.

Possible solutions, in the current version of mantis, are:
1. avoid vim. Don't write and save the `mnts` in Linux by vim.
2. try `sed -e "s/\r//g" file > newfile` to get a new file if using vim and use the new file path.

**Comment by zsxing99** [comment]
Additional info:
try `cat -A file` or `cat -T file`, `^M` indicates a CR and `$` indicates `\n`

**Comment by giorgk** [comment]
I don't use vim. This time I prepared the input files under windows. This maybe caused the problem.
Thanks for the solution.

**Comment by zsxing99** [comment]
Modifying the config files on Windows and running the model on Windows would be fine. I am concerned with future maintainance of the server. If someone log in the server and uses vim to open/save the config data or transmits Windows files to Lunix server, that will potentially cause the program to crash.

**Comment by zsxing99** [comment]
Had encountered the same issue when using `vim` on MacOS, so I believe that it will become a common issue when deploying Mantis. I still suggest adding some preventions of this problem in the input reading stage.

However, for any quick fixes, use `dos2unix` command: https://stackoverflow.com/questions/3569997/how-to-find-out-line-endings-in-a-text-file

**Comment by giorgk** [comment]
I think I have found when this happens. After reading the file lines with ```getline``` I converted them to ```std::stringstream``` type which removes those extra \r.

**Comment by zsxing99** [comment]
Issue resolved for `ini` files, but the issue persists in second-order files such as `wellSets.mnts` and `urfSets.mnts`

**Comment by giorgk** [comment]
Can you prepare a file with this issue and attach it here?
It's hard to dig into it without an example.
`ini` files a handled by boost option library. The others are handled by my code
Thanks

**Comment by zsxing99** [comment]
I have tested with some variants and it has been resolved! Thanks!
