### ISSUE TITLE
Data inconsistency

### ISSUE THREAD

**Issue by zsxing99** [giorgk/Mantis#9]
Though the data are all valid after the update, the number of data generated mismatch with the docs.

In [sample1.txt](https://github.com/zsxing99/Mantis/blob/error-report2/error_report/data/sample1.txt), which is generated by TestClient and the provided input message at [here].

And [sample2.txt](https://github.com/zsxing99/Mantis/blob/error-report2/error_report/data/sample2.txt), generated by changing `bud0` to `bud1` in the input message file.

Each result file outputs twice and has two `ENDofMSG\n`. I guess the program somewhere prints the output twice?

**Comment by giorgk** [comment]
The TestClient program prints the incoming message to a file with the hardcoded name ```testClientResults.dat``` 
However the incoming message has been rearranged into rows and columns and its not like what you get from the server.

I believe that sample1 and sample2 is the console output that you printed in a file using something like
```
.\TestClient input.dat > sample1.txt
```
If that's the case, that is expected.  
The file [TestClient.cpp](https://github.com/giorgk/Mantis/blob/master/CPP/TestClient/TestClient/TestClient.cpp)  in lines 123 and 125 prints the data as  char and  and then as string just to make sure that the conversion was ok.

In general you should not be using the console output, and the TestClient program will not be part of the procedure.

**Comment by zsxing99** [comment]
If TestClient prints twice the output, that makes sense. Yes, I was using the console output.

We haven't make backend integrated with the model yet, so doing console output is the only option for me to test now. I will do some post-processing of the data. Thanks for the check.
